SELECT USERS.EMAIL FROM USERS WHERE USERS.USERID IN(SELECT A.* FROM 
(SELECT connection.from1 FROM users,CONNECTION WHERE CONNECTION.TO1=users.UserID and users.name='Jackie Chan')
AS A CROSS JOIN
(SELECT connection.from1 FROM USERS, CONNECTION WHERE CONNECTION.TO1=USERS.USERID AND USERS.NAME='Lady Gaga')
AS B ON A.from1=B.from1);